language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: katiemei888-github
    token:
      secure: 5e4b8e5bb92e5b341698127623e84812a9515e73
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
